### ISSUE TITLE
Erro ao adicionar Gifs ou Imagens

### ISSUE THREAD

**Issue by Quagliato98** [lucas-felinto/readme_maker#9]
Bom dia, ao tentar enviar um arquivo clicando em "Enviar Arquivo", ele não abre uma aba para poder adicioná-los

**Comment by lucas-felinto** [comment]
Bom dia!

Você diz um input, o campo para o link?

Ele só abrirá um novo campo se o anterior estiver preenchido, caso esteja em branco ele não adicionará

**Comment by wejesuss** [comment]
> Bom dia, ao tentar enviar um arquivo clicando em "Enviar Arquivo", ele não abre uma aba para poder adicioná-los

Você quis dizer uma aba de escolher o arquivo? se for isso, ele não é um input de arquivo, mas pra adicionar links de imagem e gifs, mas vou trabalhar nisso :) por enquanto vc pode usar o imageKit pra disponibilizar suas imagens na web com uma url.

**Comment by lucas-felinto** [comment]
@wejesuss Perfeito! Entendi a dúvida dele. Valeu, Wermerson!

**Comment by Quagliato98** [comment]
A minha dúvida era o que o @wejesuss havia falado mesmo. Vou aprender a usar o imageKit, enquanto isso. Obrigado pelas respostas!
